baseURL = 'https://fika.works/'
languageCode = 'en-US'
title = 'FikaWorks'

disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[params]
description = "We design and deliver modular, enterprise-grade cloud solutions that integrate seamlessly with major providers such as Azure, AWS, and Google Cloud as well as Sovereign Neo-Cloud. By applying modern cloud-native engineering practices, we help businesses scale efficiently, operate securely, and innovate fasterâ€”turning complex challenges into sustainable competitive advantage."
twitter_handler = "@fikaworks"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.parser.attribute]
block = true

[outputs]
page = ["HTML"]
home = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "catppuccin-mocha"
tabWidth = 2

[menus]

[[menus.main]]
name = 'Our Services'
pageRef = '/services'
weight = 20

[[menus.main]]
name = 'Who We Are'
pageRef = '/about'
weight = 22

[[menus.main]]
name = 'FikaWorks Day'
pageRef = '/fikaworks-day'
weight = 25

[[menus.main]]
name = 'Events'
pageRef = '/events'
weight = 30

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 40

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 50


[module]
[module.hugoVersion]
extended = false
min = '0.147.0'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
